services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: app-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Tomcat
  #app:
   # build: .
    #container_name: app-tomcat-sinerji
    #depends_on:
    #  db:
    #    condition: service_healthy
    #ports:
    #  - "8080:8080"
    #volumes:
    #  - ./logs:/usr/local/tomcat/logs
    #restart: unless-stopped#

volumes:
  pgdata: